# Overview: build and create a release via Google Cloud Deploy for GKE
# NOTE: currently requires SCM triggering due to dependency on the COMMIT_SHA variable
steps:
  # Build and tag using commit sha
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '.', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats:${COMMIT_SHA}', '-f', 'Dockerfile']
    dir: 'app'
    id: build
  # Run api tests
  - name: 'asia-south1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats:${COMMIT_SHA}'
    entrypoint: python
    args: ["api_tests.py"]
    dir: 'app'
    id: apitest
  # Push the container image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
    - -c
    - |
      docker push asia-south1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats:${COMMIT_SHA} &&
      docker image inspect asia-south1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats:${COMMIT_SHA} --format '{{index .RepoDigests 0}}' > image-digest.txt &&
      cat image-digest.txt
    id: push
  - name: asia-south1-docker.pkg.dev/jmc-stage-prj/pop-stats/kritis-signer:alter
   #gcr.io/$PROJECT_ID/kritis-signer
    entrypoint: /bin/bash
    args:
    - -c
    - |
      /kritis/signer \
      -v=10 \
      -alsologtostderr \
      -image=$(/bin/cat image-digest.txt) \
      -policy=./policy/kritis/vulnz-signing-policy.yaml \
      -kms_key_name=${_KMS_KEY_NAME} \
      -kms_digest_alg=${_KMS_DIGEST_ALG} \
      -note_name=${_NOTE_NAME}
    waitFor: ['push']
    id: vulnsign
  # Create release in Google Cloud Deploy
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: /bin/bash
    args:
    - -c
    - |
      gcloud deploy releases create rel-${SHORT_SHA} \
      --delivery-pipeline=security-demo-pipelne \
      --region=asia-south1 \
      --annotations=commitId=${REVISION_ID} \
      --images=pop-stats=$(/bin/cat image-digest.txt)
    waitFor: ['vulnsign']
images:
- asia-south1-docker.pkg.dev/$PROJECT_ID/pop-stats/pop-stats:${COMMIT_SHA}
options:
  requestedVerifyOption: VERIFIED
  pool:
    name: 'projects/$PROJECT_ID/locations/asia-south1/workerPools/gcp-cicd-demo'
# Set these variables in your trigger or directly in the substitutions stanza below: 
substitutions:
   _KMS_KEY_NAME: "projects/jmc-stage-prj/locations/asia-south1/keyRings/gcp-cicd-demo/cryptoKeys/test-key/cryptoKeyVersions/1"
   _KMS_DIGEST_ALG: "SHA512"
   _NOTE_NAME: projects/jmc-stage-prj/notes/secure-cicd-attestor-note
     #projects/jmc-stage-prj/notes/vulnz-note
    
